spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/medi-shop
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
 
server:
  port: 8181
  

  
    